-- Seed featured Summer 2026 seasonal guide (run once after featured migration)

insert into public.anime_news_articles (
  slug,
  source_guid,
  source_url,
  source_author,
  source_category,
  cover_image_url,
  topics,
  published_at,
  status,
  is_featured,
  featured_order,
  title_en,
  title_ar,
  title_ja,
  excerpt_en,
  excerpt_ar,
  excerpt_ja,
  story_en,
  story_ar,
  story_ja,
  feed_synced_at,
  updated_at
)
values (
  'summer-anime-2026-crunchyroll',
  'clashanime:featured:summer-anime-2026-crunchyroll',
  'https://www.crunchyroll.com/ar/news/seasonal-lineup/2026/6/17/summer-anime-2026-crunchyroll',
  'Crunchyroll News',
  'Seasonal Lineup',
  'https://a.storyblok.com/f/178900/1241x797/4783d2bad2/crunchyroll-news-newtype-cover-summer-2026.png',
  array['seasonal-lineup', 'summer-2026', 'simulcast', 'anime-news'],
  '2026-06-17T12:00:00+00'::timestamptz,
  'published',
  true,
  100,
  'Summer 2026 Anime Season — Crunchyroll Simulcast Guide',
  'دليل موسم صيف 2026 — بث Crunchyroll',
  '2026年夏アニメ — Crunchyroll配信ガイド',
  '50+ new and returning titles land on Crunchyroll this summer — from Black Torch and Smoking Behind the Supermarket to Mushoku Tensei Season 3 and One Piece Elbaph Arc Part 2.',
  'أكثر من 50 عنواناً جديداً وعائداً على Crunchyroll هذا الصيف — من Black Torch وSmoking Behind the Supermarket إلى Mushoku Tensei موسم 3 وOne Piece Elbaph Arc Part 2.',
  'Crunchyrollの夏2026は50作品超。Black Torch、Smoking Behind the Supermarket、無職転生S3、ONE PIECEエルバフ編など。',
  E'Crunchyroll''s Summer 2026 lineup is one of the biggest seasonal drops of the year. More than fifty simulcasts are scheduled between late June and August, mixing bold new adaptations with returning fan favorites and ongoing spring hits.\n\nHighlights debuting in early July include Black Torch (July 4), Jaadugar: A Witch in Mongolia (July 4), Skeleton Knight in Another World Season 2 (July 4), Smoking Behind the Supermarket with You (July 9), Victoria of Many Faces (July 7), and Tomb Raider King (July 8).\n\nMajor returning arcs include Mushoku Tensei: Jobless Reincarnation Season 3, Re:ZERO Season 4 Part 2, Clevatess Season 2, Saga of Tanya the Evil Season 2, and You and I Are Polar Opposites Season 2.\n\nSpring carryovers still simulcasting weekly: One Piece — Elbaph Arc Part 2, That Time I Got Reincarnated as a Slime Season 4, Daemons of the Shadow Realm, Digimon Beatbreak, Ascendance of a Bookworm, and more.\n\nUse this guide on ClashAnime to track release energy, join episode clashes on /tracker, and upload your best clips when new episodes drop. Full calendar and trailers live on Crunchyroll News.',
  E'أعلن Crunchyroll عن موسم صيف 2026 بأحد أضخم جداول البث المباشر هذا العام. أكثر من خمسين عملاً بين أواخر يونيو وأغسطس، يجمع بين اقتباسات جديدة وعودة سلاسل محبوبة واستمرار أعمال الربيع.\n\nأبرز الانطلاقات في يوليو: Black Torch (4 يوليو)، Jaadugar: A Witch in Mongolia (4 يوليو)، Skeleton Knight in Another World الموسم 2 (4 يوليو)، Smoking Behind the Supermarket with You (9 يوليو)، Victoria of Many Faces (7 يوليو)، وTomb Raider King (8 يوليو).\n\nعودة مهمة تشمل Mushoku Tensei: Jobless Reincarnation الموسم 3، Re:ZERO الموسم 4 الجزء 2، Clevatess الموسم 2، Saga of Tanya the Evil الموسم 2، وYou and I Are Polar Opposites الموسم 2.\n\nأعمال الربيع التي ما زالت تُبث: One Piece — Elbaph Arc Part 2، That Time I Got Reincarnated as a Slime الموسم 4، Daemons of the Shadow Realm، Digimon Beatbreak، Ascendance of a Bookworm، وغيرها.\n\nاستخدم هذا الدليل على ClashAnime لمتابعة الإصدارات، وادخل نزالات الحلقات على /tracker، وارفع أفضل لقطاتك عند نزول حلقات جديدة. التقويم الكامل والتريلرات على Crunchyroll News.',
  E'Crunchyrollの2026年夏シーズンは、6月下旬から8月にかけて50作品以上のSimulcastが予定されている大型ラインナップです。\n\n7月初旬の注目作：Black Torch（7/4）、Jaadugar: A Witch in Mongolia（7/4）、Skeleton Knight in Another World S2（7/4）、Smoking Behind the Supermarket with You（7/9）、Victoria of Many Faces（7/7）、Tomb Raider King（7/8）。\n\n続編・復活作：無職転生 S3、Re:ZERO S4 Part 2、Clevatess S2、幼女戦記 S2、正反対な君と僕 S2 など。\n\n春から継続：ONE PIECE エルバフ編 Part 2、転スラ S4、Daemons of the Shadow Realm、Digimon Beatbreak、本好きの下剋上 など。\n\nClashAnimeで新作を追い、/trackerのエピソードクラッシュに参加し、配信直後のクリップをアップロードしましょう。',
  now(),
  now()
)
on conflict (source_guid) do update set
  slug = excluded.slug,
  source_url = excluded.source_url,
  source_author = excluded.source_author,
  source_category = excluded.source_category,
  cover_image_url = excluded.cover_image_url,
  topics = excluded.topics,
  published_at = excluded.published_at,
  status = excluded.status,
  is_featured = excluded.is_featured,
  featured_order = excluded.featured_order,
  title_en = excluded.title_en,
  title_ar = excluded.title_ar,
  title_ja = excluded.title_ja,
  excerpt_en = excluded.excerpt_en,
  excerpt_ar = excluded.excerpt_ar,
  excerpt_ja = excluded.excerpt_ja,
  story_en = excluded.story_en,
  story_ar = excluded.story_ar,
  story_ja = excluded.story_ja,
  feed_synced_at = excluded.feed_synced_at,
  updated_at = excluded.updated_at;
