import type { SeasonalLineupEntry } from "@/lib/animeNews/seasonalLineupTypes";

/** Curated from Crunchyroll Summer 2026 press release — refreshed on each daily sync. */
export function buildSummer2026SeasonalLineup(): SeasonalLineupEntry[] {
  return [
    { title: "Heroine? Saint? No, I'm an All-Works Maid (And Proud of It)!", premiereDate: "2026-06-24", category: "new" },
    { title: "From Overshadowed to Overpowered: Second Reincarnation of a Talentless Sage", premiereDate: "2026-06-25", category: "new" },
    { title: "The Oblivious Saint Can't Contain Her Power", premiereDate: "2026-06-30", category: "new" },
    { title: "Hana-Kimi Season 2", premiereDate: "2026-07-01", category: "returning" },
    { title: "The Villager of Level 999", premiereDate: "2026-07-01", category: "new" },
    { title: "KAIJU GIRL CARAMELISE", premiereDate: "2026-07-02", category: "new" },
    { title: "Bungo Stray Dogs WAN! 2", premiereDate: "2026-07-02", category: "returning" },
    { title: "The Exiled Heavy Knight Knows How to Game the System", premiereDate: "2026-07-02", category: "new" },
    { title: "Dara-san of Reiwa", premiereDate: "2026-07-02", category: "new" },
    { title: "I Became a Legend after My 10 Year-Long Last Stand", premiereDate: "2026-07-03", category: "new" },
    { title: "Sorry About My Little Brothers", premiereDate: "2026-07-03", category: "new" },
    { title: "BLACK TORCH", premiereDate: "2026-07-04", category: "new" },
    { title: "Jaadugar: A Witch in Mongolia", premiereDate: "2026-07-04", category: "new" },
    { title: "Skeleton Knight in Another World Season 2", premiereDate: "2026-07-04", category: "returning" },
    { title: "GROW UP SHOW -Sunflower Circus-", premiereDate: "2026-07-04", category: "new" },
    { title: "Rich Girl Caretaker: I'm Secretly the Caregiver of the Most Popular Girl in This Rich Kid School", premiereDate: "2026-07-04", category: "new" },
    { title: "The Cat and the Dragon", premiereDate: "2026-07-04", category: "new" },
    { title: "The Duke's Son Claims He Won't Love Me Yet Showers Me with Adoration", premiereDate: "2026-07-04", category: "new" },
    { title: "The Ogre's Bride", premiereDate: "2026-07-04", category: "new" },
    { title: "Goodbye, Lara", premiereDate: "2026-07-05", category: "new" },
    { title: "Mushoku Tensei: Jobless Reincarnation Season 3", premiereDate: "2026-07-05", category: "returning" },
    { title: "The World's Strongest Rearguard", premiereDate: "2026-07-05", category: "new" },
    { title: "You and I Are Polar Opposites Season 2", premiereDate: "2026-07-05", category: "returning" },
    { title: "Love Unseen Beneath the Clear Night Sky", premiereDate: "2026-07-06", category: "new" },
    { title: "The Insipid Prince's Furtive Grab for The Throne", premiereDate: "2026-07-06", category: "new" },
    { title: "I Want to Love You Till Your Dying Day", premiereDate: "2026-07-07", category: "new" },
    { title: "Victoria of Many Faces", premiereDate: "2026-07-07", category: "new" },
    { title: "Young Ladies Don't Play Fighting Games", premiereDate: "2026-07-07", category: "new" },
    { title: "Clevatess Season 2", premiereDate: "2026-07-08", category: "returning" },
    { title: "Tomb Raider King", premiereDate: "2026-07-08", category: "new" },
    { title: "Saga of Tanya the Evil Season 2", premiereDate: "2026-07-08", category: "returning" },
    { title: "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs Season 2", premiereDate: "2026-07-08", category: "returning" },
    { title: "Smoking Behind the Supermarket with You", premiereDate: "2026-07-09", category: "new" },
    { title: "MEBIUS DUST", premiereDate: "2026-07-09", category: "new" },
    { title: "Hanaori-san Still Wants to Fight in the Next Life", premiereDate: "2026-07-11", category: "new" },
    { title: "Though I Am an Inept Villainess", premiereDate: "2026-07-12", category: "new" },
    { title: "Re:ZERO -Starting Life in Another World- Season 4 Part 2", premiereDate: "2026-08-12", category: "returning" },
    { title: "The Elusive Samurai Season 2", premiereDate: "coming-soon", category: "coming-soon" },
    { title: "Oh Boy, Was I Wrong About Her", premiereDate: "coming-soon", category: "coming-soon" },
    { title: "Ascendance of a Bookworm: Adopted Daughter of an Archduke", premiereDate: null, category: "continuing", weekday: "Saturdays" },
    { title: "Case Closed (Detective Conan)", premiereDate: null, category: "continuing", weekday: "Saturdays" },
    { title: "Daemons of the Shadow Realm", premiereDate: null, category: "continuing", weekday: "Saturdays" },
    { title: "Digimon Beatbreak", premiereDate: null, category: "continuing", weekday: "Saturdays" },
    { title: "Star Detective Precure!", premiereDate: null, category: "continuing", weekday: "Saturdays" },
    { title: "Welcome to Demon School! Iruma-kun Season 4", premiereDate: null, category: "continuing", weekday: "Saturdays" },
    { title: "One Piece – Elbaph Arc Part 2", premiereDate: null, category: "continuing", weekday: "Sundays" },
    { title: "The Classroom of a Black Cat and a Witch", premiereDate: null, category: "continuing", weekday: "Sundays" },
    { title: "Liar Game", premiereDate: null, category: "continuing", weekday: "Mondays" },
    { title: "RILAKKUMA", premiereDate: null, category: "continuing", weekday: "Fridays" },
    { title: "That Time I Got Reincarnated as a Slime Season 4", premiereDate: null, category: "continuing", weekday: "Fridays" },
    { title: "The Drops of God", premiereDate: null, category: "continuing", weekday: "Fridays" },
  ];
}

export const SUMMER_2026_LINEUP_COUNT = buildSummer2026SeasonalLineup().length;
